---
abstract: 'Background job processing based on Resque, using Stomp'
author:
  - 'William Wolf <throughnothing@gmail.com>'
build_requires:
  Test::More: 0
  perl: v5.10.0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.113640'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sque
requires:
  Any::Moose: 0
  JSON: 0
  Net::STOMP::Client: 0
  Try::Tiny: 0
  UNIVERSAL::require: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/throughnothing/Sque/issues
  homepage: http://metacpan.org/release/Sque/
  repository: git://github.com/throughnothing/Sque.git
version: 0.002
